# Generated by Django 2.0.8 on 2018-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageURL',
            field=models.TextField(default='/', verbose_name='/'),
            preserve_default=False,
        ),
    ]
