# Generated by Django 2.0.8 on 2018-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageURL',
            field=models.TextField(),
        ),
    ]
