# Generated by Django 2.0.8 on 2018-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180821_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageURL',
            field=models.URLField(),
        ),
    ]
