# Generated by Django 2.0.8 on 2018-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180821_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='Link'),
            preserve_default=False,
        ),
    ]
