# Generated by Django 2.0.8 on 2018-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkdsk',
            field=models.TextField(default='Link description'),
            preserve_default=False,
        ),
    ]
