# Generated by Django 2.0.8 on 2018-08-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_linkdsk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
    ]
